# Generated by Django 2.0.6 on 2018-07-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=250)),
                ('channel_title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('channel_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('chennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Channel')),
            ],
        ),
    ]
